CREATE TABLE users
(
  username VARCHAR(64) NOT NULL PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  department VARCHAR(64),
  enabled BOOLEAN NOT NULL
);

-- 在庫品マスタ
CREATE TABLE stock_master
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  item_code VARCHAR(64) NOT NULL UNIQUE,
  item_name VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  model_number VARCHAR(64),
  manufacturer VARCHAR(64),
  current_stock DECIMAL(14,2) NOT NULL DEFAULT 0,
  location VARCHAR(64) DEFAULT '-',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 設備品マスタ
CREATE TABLE asset_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(255) UNIQUE,
    asset_name VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(64) DEFAULT '-',
    model_number VARCHAR(255),
    supplier VARCHAR(64) NOT NULL DEFAULT '-',
    category VARCHAR(100) NOT NULL,
    serial_number VARCHAR(100),
    regist_date DATE,
    purchase_price DECIMAL(14, 2) NOT NULL DEFAULT 0.00;
    status VARCHAR(50) NOT NULL,
    location VARCHAR(100) DEFAULT '-',
    last_calibration_date DATE,
    next_calibration_due_date DATE,
    monitored BOOLEAN NOT NULL,
    remarks VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- 発注登録ヘッダー
CREATE TABLE purchase_order
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(64) NOT NULL UNIQUE,
  supplier VARCHAR(64) NOT NULL,
  order_subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,
  order_date DATE NOT NULL,
  shipping_fee DECIMAL(10,2) NOT NULL DEFAULT 0,
  operator VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT '未完了',
  remarks VARCHAR(255),
  created_at DATE DEFAULT (CURRENT_DATE)
);

-- 発注明細
CREATE TABLE purchase_order_detail
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  order_no VARCHAR(64) NOT NULL,
  item_code VARCHAR(64),
  item_name VARCHAR(128),
  model_number VARCHAR(64),
  category VARCHAR(64),
  quantity DECIMAL(14,2) NOT NULL,
  purchase_price DECIMAL(10,2) NOT NULL,
  received_quantity DECIMAL(14,2) DEFAULT 0,
  status VARCHAR(32) DEFAULT '未入庫',
  remarks VARCHAR(255),
  CONSTRAINT fk_purchase_order_detail_order_no
    FOREIGN KEY (order_no)
    REFERENCES purchase_order (order_no)
);

-- 在庫品トランザクション
CREATE TABLE inventory_transaction
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  transaction_id VARCHAR(64) NOT NULL UNIQUE,
  item_code VARCHAR(64) NOT NULL,
  transaction_type VARCHAR(32) NOT NULL,
  quantity DECIMAL(14, 2) NOT NULL,
  operator VARCHAR(64) NOT NULL,
  transaction_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  manufacturer VARCHAR(64),
  supplier VARCHAR(64),
  purchase_price DECIMAL(10, 2),
  order_no VARCHAR(64),
  remarks VARCHAR(255),
  CONSTRAINT fk_inventory_transaction_order_no
    FOREIGN KEY (order_no) REFERENCES purchase_order (order_no),
  CONSTRAINT fk_inventory_transaction_item_code
    FOREIGN KEY (item_code) REFERENCES stock_master (item_code)
);

-- 番号マスタ
CREATE TABLE numbering_master
(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  department_code VARCHAR(10) NOT NULL,
  numbering_type VARCHAR(20) NOT NULL,
  fiscal_year INTEGER NOT NULL,
  current_decimal_number BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  version INTEGER DEFAULT 0
);